DROP TABLE IF EXISTS mete_reading CASCADE;

CREATE TABLE meter_reading (
    account_id bigint,
    date date,
    id bigint generated by default as identity,
    meter_id bigint,
    reading bigint,
    reading_type enum ('ELECTRICITY','GAS'),

    primary key (id)
);